### ISSUE TITLE
pnpm dev 运行报错

### ISSUE THREAD

**Issue by MissGwen** [hu-snail/snail-uni#1]
node -v   v22.12.0
pnpm -v  v9.15.1

`请注意运行模式下，因日志输出、sourcemap 以及未压缩源码等原因，性能和包体积，均不及发行模式。若要正式发布，请点击发行菜单或使用 cli 发布命令进行发布
正在编译中...
error during build:
Error [ERR_INTERNAL_ASSERTION]: Unexpected status of a module that is imported again after being required. Status = 0
This is caused by either a bug in Node.js or incorrect usage of Node.js internals.
Please open an issue with this stack trace at https://github.com/nodejs/node/issues

    at Function.fail (node:internal/assert:17:9)
    at ModuleJobSync.run (node:internal/modules/esm/module_job:378:12)
    at onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:547:42)
    at async import (C:\Users\MissGwen\Desktop\snai-uni-app\node_modules\.pnpm\jiti@2.0.0-beta.3\node_modules\jiti\dist\jiti.cjs:1:195631)
    at async C:/Users/MissGwen/Desktop/snai-uni-app/pages.config.ts:1:207
    at async Function.import (C:\Users\MissGwen\Desktop\snai-uni-app\node_modules\.pnpm\jiti@2.0.0-beta.3\node_modules\jiti\dist\jiti.cjs:1:195631)
    at async Module.loader (file:///C:/Users/MissGwen/Desktop/snai-uni-app/node_modules/.pnpm/importx@0.4.4/node_modules/importx/dist/chunks/jiti.mjs:11:15)
    at async Module.importx (file:///C:/Users/MissGwen/Desktop/snai-uni-app/node_modules/.pnpm/importx@0.4.4/node_modules/importx/dist/index.mjs:179:19)
    at async C:\Users\MissGwen\Desktop\snai-uni-app\node_modules\.pnpm\unconfig@0.5.5\node_modules\unconfig\dist\index.cjs:177:21
    at async loadConfigFile (C:\Users\MissGwen\Desktop\snai-uni-app\node_modules\.pnpm\unconfig@0.5.5\node_modules\unconfig\dist\index.cjs:176:18)
    at async Object.load (C:\Users\MissGwen\Desktop\snai-uni-app\node_modules\.pnpm\unconfig@0.5.5\node_modules\unconfig\dist\index.cjs:105:24)
    at async PageContext.loadUserPagesConfig (C:\Users\MissGwen\Desktop\snai-uni-app\node_modules\.pnpm\@uni-helper+vite-plugin-uni-pages@0.2.28_vite@5.2.8_@types+node@22.10.2_sass@1.78.0_terser@5.37.0_\node_modules\@uni-helper\vite-plugin-uni-pages\dist\index.cjs:369:33)
    at async PageContext.updatePagesJSON (C:\Users\MissGwen\Desktop\snai-uni-app\node_modules\.pnpm\@uni-helper+vite-plugin-uni-pages@0.2.28_vite@5.2.8_@types+node@22.10.2_sass@1.78.0_terser@5.37.0_\node_modules\@uni-helper\vite-plugin-uni-pages\dist\index.cjs:534:5)
    at async configResolved (C:\Users\MissGwen\Desktop\snai-uni-app\node_modules\.pnpm\@uni-helper+vite-plugin-uni-pages@0.2.28_vite@5.2.8_@types+node@22.10.2_sass@1.78.0_terser@5.37.0_\node_modules\@uni-helper\vite-plugin-uni-pages\dist\index.cjs:638:7)
    at async Promise.all (index 0)
    at async resolveConfig (file:///C:/Users/MissGwen/Desktop/snai-uni-app/node_modules/.pnpm/vite@5.2.8_@types+node@22.10.2_sass@1.78.0_terser@5.37.0/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:68410:5)
    at async Module.build (file:///C:/Users/MissGwen/Desktop/snai-uni-app/node_modules/.pnpm/vite@5.2.8_@types+node@22.10.2_sass@1.78.0_terser@5.37.0/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:67273:20)
    at async CAC.runDev (C:\Users\MissGwen\Desktop\snai-uni-app\node_modules\.pnpm\@dcloudio+vite-plugin-uni@3.0.0-4030620241128001_postcss@8.4.49_rollup@4.29.1_vite@5.2.8_@typ_meryxf5w2pko74camwwwy4wgfm\node_modules\@dcloudio\vite-plugin-uni\dist\cli\action.js:63:30)
 ELIFECYCLE  Command failed with exit code 1.`

**Comment by T-loml** [comment]
node version 降低

**Comment by kewab** [comment]
Node版本太低不行，太高也不行吗？
